a=18
leftguess=9
guess=0

print("You will be given 9 guesses to guess a number generated by the program.\n")
print("-Start now-\n")
inp1 = int(input("Your guess:\n"))

while (1):
    if inp1==a:
     print("Congrats you guessed the correct number!\n")
     print("You guessed",guess+1,"times\n")
     break

    elif guess==8:
     print("game over\n")
     print("rerun the program to try again\n")
     break

    elif inp1 < a:
     print("This number is smaller than expected\n")
     print("Please try again\n")
     leftguess = leftguess - 1
     guess = guess + 1
     print("Number of guesses left:", leftguess)
     inp1 = int(input("Your guess:\n"))
     continue

    elif inp1 > a:
     print("This number is greater than expected\n")
     print("Please try again\n")
     leftguess = leftguess - 1
     guess = guess + 1
     print("Number of guesses left:", leftguess)
     inp1 = int(input("Your guess:\n"))
     continue

    else:
        print("Invalid input")
        print("Try again\n")
        continue